### ISSUE TITLE
make: *** [Makefile:42: target/nmdc_biosample_generated.yaml] Error 1

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/DataHarmonizer#19]
> Traceback (most recent call last):
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/bin/gen-yaml", line 8, in <module>
    sys.exit(cli())
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/linkml/generators/yamlgen.py", line 45, in cli
    gen = YAMLGenerator(yamlfile, **args)
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/linkml/generators/yamlgen.py", line 24, in __init__
    super().__init__(schema, **kwargs)
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/linkml/utils/generator.py", line 91, in __init__
    loader = SchemaLoader(schema, self.base_dir, useuris=useuris, importmap=importmap, logger=self.logger,
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/linkml/utils/schemaloader.py", line 52, in __init__
    self.schema = load_raw_schema(data, base_dir=base_dir, merge_modules=mergeimports,
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/linkml/utils/rawloader.py", line 69, in load_raw_schema
    schema = yaml_loader.load(copy.deepcopy(data) if isinstance(data, dict) else data,
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/linkml_runtime/loaders/yaml_loader.py", line 22, in load
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/linkml_runtime/loaders/loader_root.py", line 60, in load_source
    data_as_dict = loader(data, metadata)
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/linkml_runtime/loaders/yaml_loader.py", line 16, in loader
    return yaml.load(StringIO(data), DupCheckYamlLoader) if isinstance(data, str) else data
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/mark/.cache/pypoetry/virtualenvs/linkml-round-trips-2m4fR-mZ-py3.9/lib/python3.9/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here

**Comment by turbomam** [comment]
On my Linux desktop:

> The currently activated Python version 3.8.10 is not supported by the project (^3.9).
Trying to find and use a compatible version. 
Using python3.9 (3.9.5)

That's getting injected into [target/nmdc_biosample.yaml](target/nmdc_biosample.yaml)

**Comment by turbomam** [comment]
`make all` works when I run `poetry env use /usr/bin/python3.9` first
